import { PricingPlan } from "@/types"

export const PRICING_PLANS: PricingPlan[] = [
  {
    id: "free",
    name: "Free",
    description: "Great for getting started. Explore all features with limited usage.",
    price: 0,
    tokens: 5,
    pricePerToken: "$0.00",
    features: [
      "Access to all features",
      "5 tokens included",
      "Text input support",
      "Basic code assistance",
      "Community support",
    ],
  },
  {
    id: "professional",
    name: "Professional",
    description: "For active job seekers preparing for multiple interviews.",
    price: 149,
    tokens: 200,
    pricePerToken: "$0.75",
    popular: true,
    features: [
      "Unlimited access to App",
      "200 tokens / month",
      "All input types",
      "Voice & screenshot analysis",
      "Priority response time",
      "Advanced reasoning",
      "Code optimization tips",
      "Email support",
    ],
  },
  {
    id: "enterprise",
    name: "Enterprise",
    description: "For power users and teams with unlimited interview preparation needs.",
    price: 199,
    tokens: 500,
    pricePerToken: "$0.40",
    features: [
      "Unlimited access to App",
      "500 tokens / month",
      "All input types",
      "Voice & screenshot analysis",
      "Fastest response time",
      "Advanced reasoning",
      "System design help",
      "Priority support",
      "Custom integrations",
    ],
  },
]

export const PROGRAMMING_LANGUAGES = [
  { value: "javascript", label: "JavaScript" },
  { value: "typescript", label: "TypeScript" },
  { value: "python", label: "Python" },
  { value: "java", label: "Java" },
  { value: "cpp", label: "C++" },
  { value: "csharp", label: "C#" },
  { value: "go", label: "Go" },
  { value: "rust", label: "Rust" },
  { value: "php", label: "PHP" },
  { value: "ruby", label: "Ruby" },
  { value: "swift", label: "Swift" },
  { value: "kotlin", label: "Kotlin" },
  { value: "sql", label: "SQL" },
  { value: "flutter", label: "Flutter/Dart" },
  { value: "html", label: "HTML/CSS" },
  { value: "other", label: "Other" },
] as const

export const KEYBOARD_SHORTCUTS = [
  { key: "CMD/CTRL + 2", action: "Activate microphone" },
  { key: "CMD/CTRL + 3", action: "Capture PC audio" },
  { key: "CMD/CTRL + 4", action: "Take screenshot" },
  { key: "CMD/CTRL + 9", action: "Toggle app visibility" },
  { key: "CMD/CTRL + TAB", action: "Clear input" },
  { key: "CMD/CTRL + SPACE", action: "Submit request" },
] as const
